name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  Release:
    if: github.event.pull_request.merged == true
    uses: gesslar/Maint/.github/workflows/Release.yaml@main
    secrets: inherit
    with:
      package_manager: "auto"
    permissions:
      contents: write
